FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    bash \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

# Enable pnpm via corepack
RUN corepack enable

# Copy dependency files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy app source
COPY . .

EXPOSE 3000

RUN mkdir /workspace

CMD ["pnpm", "run", "start"]